spring:
  application:
    name: order-management-system
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      database: oms_events

server:
  port: 8080

oms:
  order:
    max-items-per-order: 50
    default-status: PENDING
  routing:
    enabled: false
