spring:
  application:
    name: order-management-system
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      database: oms_events

server:
  port: 8080

oms:
  order:
    max-items-per-order: 50
    default-status: PENDING
  routing:
    enabled: false
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:ThisIsASecretKeyForJWTSigningThatShouldBeAtLeast256BitsLongForHS256}
      expiration-ms: 86400000 # 24 hours
      refresh-expiration-ms: 604800000 # 7 days
