spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/omsdb
    driver-class-name: org.postgresql.Driver
    username: oms
    password: oms
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/oms_events
